add drive discovery
minio/direct-csi pull request #32
Opened 2020-10-29 05:19 UTC by wlan0

@nitisht @Praveenrajmani 

This solves the most complex part of drive discovery. Currently it extracts the partitionNumber, modelNumber and serialNumber. Next step is to parse the appropriate files for the rest of the fields. I figured, this should be enough to proceed on blocked tasks. I'll continue adding more fields in the meantime.

2020-10-29 05:21 UTC, wlan0 commented
Here is what the output looks like

```
wlan0:~/code/go/src/github.com/minio/direct-csi$ go test github.com/minio/direct-csi/pkg/node
[ 
 {             
  "metadata": {             
   "creationTimestamp": null
  },                                                                     
  "modelNumber": "WDC PC SN730 SDBQNTY-512G-1001",
  "serialNumber": "eui.001b448b467b6b1f",
  "name": "nvme0n1",
  "ownerNode": {},     
  "totalCapacity": "0",
  "freeCapacity": "0",
  "volumes": null,         
  "path": "/dev/nvme0n1",
  "formatted": false,        
  "rootPartition": "nvme0n1",
  "PartitionNum": 1,
  "driveStatus": ""
 },
 {                              
  "metadata": {           
   "creationTimestamp": null
  },                                                                     
  "modelNumber": "WDC PC SN730 SDBQNTY-512G-1001-part1",
  "serialNumber": "eui.001b448b467b6b1f-part1",  
  "name": "nvme0n1p1",
  "ownerNode": {},
  "totalCapacity": "0",
  "freeCapacity": "0",
  "volumes": null,
  "path": "/dev/nvme0n1p1",
  "formatted": false,
  "rootPartition": "nvme0n1",
  "PartitionNum": 1,
  "driveStatus": ""
 },
 {
  "metadata": {
   "creationTimestamp": null
  },
  "modelNumber": "WDC PC SN730 SDBQNTY-512G-1001-part2",
  "serialNumber": "eui.001b448b467b6b1f-part2",
  "name": "nvme0n1p2",
  "ownerNode": {},
  "totalCapacity": "0",
  "freeCapacity": "0",
  "volumes": null,
  "path": "/dev/nvme0n1p2",
  "formatted": false,
  "rootPartition": "nvme0n1",
  "PartitionNum": 2,
  "driveStatus": ""
 }
]
```

2020-10-29 12:22 UTC, Praveenrajmani approved these changes
Just a minor nit. Which i guess was for printing the response. Tested and LGTM.

2020-10-29 12:22 UTC, Praveenrajmani commented on pkg/node/node_test.go
> +	t.Error(err)
```suggestion
	if err != nil {
		t.Error(err)
	}
```

2020-10-30 07:08 UTC, harshavardhana requested changes
Why not use this? https://github.com/jaypipes/ghw#block-storage looks like a fully complete library with enough details needed.

2020-10-30 07:55 UTC, nitisht approved these changes

2020-10-30 07:56 UTC, nitisht commented
> Why not use this? https://github.com/jaypipes/ghw#block-storage looks like a fully complete library with enough details needed.

We'll use this, but for now, need to merge the PR so I can proceed with current task

2020-10-31 05:42 UTC, merged