Update the types
minio/direct-csi pull request #42
Opened 2020-11-11 04:35 UTC by nitisht

Update DirectCSIDrive and DirectCSIVolume types to capture
required info.

2020-11-12 03:36 UTC, wlan0 requested changes

2020-11-12 03:36 UTC, wlan0 commented on pkg/apis/direct.csi.min.io/v1alpha1/types.go
> +	FormatInfo FormatInfo `json:"formatInfo,omitempty"`
Following our discussion on #direct-csi on slack, let us rename this to RequestedFormat

2020-11-12 03:36 UTC, wlan0 commented on pkg/apis/direct.csi.min.io/v1alpha1/types.go
> +	Forced bool `json:forced,omitempty`
Force bool

2020-11-12 08:52 UTC, nitisht commented
@wlan0 addressed the comments, PTAL

2020-11-13 20:33 UTC, wlan0 approved these changes
LGTM

2020-11-13 20:35 UTC, wlan0 commented
Closing this since the commit was already merged as a part of other PR

2020-11-13 20:35 UTC, closed without merging