Format/Re-format the drives on request
minio/direct-csi pull request #49
Opened 2020-11-18 13:35 UTC by Praveenrajmani

- Format the unformatted drives while adding drives with filesystem being set in the requested format
- Reformat the drive if the filesystem and force is set in the requested format

Steps to test (By directly applying the directcsi yaml)

2020-11-18 17:04 UTC, nitisht submitted a review, later dismissed

2020-11-19 03:27 UTC, wlan0 commented on build.sh
> +apt-get -y install xfsprogs
put this in the dockerfile

2020-11-19 03:28 UTC, wlan0 commented on pkg/node/node_controller.go
> +				if err := UnmountIfMounted(new.Mountpoint); err != nil {
we should first check if there are any volumes being used from this drive before unmounting.

2020-11-19 03:30 UTC, wlan0 requested changes
ensure that there are no volumes in use from a drive before unmounting it

2020-11-26 16:22 UTC, Praveenrajmani commented
@nitisht  @wlan0 Can we get this PR merged? I can send a separate PR for purge.

2020-11-26 16:48 UTC, nitisht approved these changes

2020-11-27 23:24 UTC, wlan0 commented on pkg/controller/controller_test.go
> +func TestFilterDrivesByRequestedFormat(t1 *testing.T) {
:+1

2020-11-27 23:25 UTC, wlan0 approved these changes

2020-11-30 03:26 UTC, Praveenrajmani commented
Fixed the conflicts. Can you re-approve @wlan0 @nitisht

2020-11-30 03:32 UTC, wlan0 approved these changes

2020-11-30 03:37 UTC, merged