Add support for mountOptions in drive add command
minio/direct-csi pull request #53
Opened 2020-11-24 12:52 UTC by nitisht

Also update the drive list output table to show
servers in a separate column.

2020-11-24 17:56 UTC, wlan0 commented
@nitisht looks good overall. You need to regenerate the CRDs using ./hack/update-codegen.sh

2020-11-24 17:57 UTC, wlan0 requested changes
CRD spec needs to be regenerated using ./hack/update-codegen.sh

2020-11-25 06:25 UTC, nitisht commented
> CRD spec needs to be regenerated using ./hack/update-codegen.sh

Done

2020-11-25 06:54 UTC, wlan0 commented
LGTM

2020-11-25 06:57 UTC, wlan0 requested changes

2020-11-25 06:57 UTC, wlan0 commented on config/crd/direct.csi.min.io_directcsidrives.yaml
> +                type: string
this should be list

2020-11-25 07:06 UTC, wlan0 approved these changes

2020-11-25 07:07 UTC, merged